#!/bin/bash
# shellcheck disable=SC2086,SC2001,SC2154,SC1091
set -e

root=$1
shift

. "/usr/share/grub/grub-mkconfig_lib"
. /etc/default/grub

export TEXTDOMAIN=grub
export TEXTDOMAINDIR="${datarootdir}/locale"

TITLE="BlissOS $(grep 'ro.bliss.version=' /system/build.prop | awk -F'=' '{print $2}')"

ADVANCED_ARGS=(
	"Debug mode: DEBUG=2 androidboot.enable_console=1"
	"No Modeset: nomodeset"
	"No hwaccel: HWACCEL=0"
)

RECOVERY_ARGS=(
	""
	"Debug mode: DEBUG=2 androidboot.enable_console=1"
	"RGBX_8888 color mode: androidboot.pixel_format=RGBX_8888"
	"ABGR_8888 color mode: androidboot.pixel_format=ABGR_8888"
	"ARGB_8888 color mode: androidboot.pixel_format=ARGB_8888"
	"BGRA_8888 color mode: androidboot.pixel_format=BGRA_8888"
	"RGBA_8888 color mode: androidboot.pixel_format=RGBA_8888"
	"BGRX_8888 color mode: androidboot.pixel_format=BGRX_8888"
)

# Extra indentation to add to menu entries in a submenu. We're not in a submenu
# yet, so it's empty. In a submenu it will be equal to '\t' (one tab).
ROOT_DEVICE=$GRUB_DEVICE
ROOT_UUID=$(${grub_probe} --device "$GRUB_DEVICE" --target=fs_uuid 2>/dev/null)
ROOT_PARTUUID=$(${grub_probe} --device "$GRUB_DEVICE" --target=partuuid 2>/dev/null)

[ "$ROOT_UUID" ] &&
  ROOT_DEVICE="UUID=$ROOT_UUID"

RECOVERY_PARAMETERS="androidboot.mode=recovery androidboot.force_normal_boot=0"

conf=efi/EFI/refind/refind.conf
CONFIG_FILE=$root/boot/$conf
CMDLINE=$*

cat <<EOF >>"$CONFIG_FILE"

menuentry "$TITLE" {
  icon /EFI/refind/icons/blissos.png
  volume $ROOT_PARTUUID
  loader /kernel_a
  initrd /initrd_a
  options "androidboot.mode=normal $CMDLINE ROOT=$ROOT_DEVICE SRC=$SRC androidboot.slot_suffix=_a root=/dev/ram0"
  submenuentry "Recovery mode" {
    add_options "$RECOVERY_PARAMETERS"
  }
EOF

for arg in "${ADVANCED_ARGS[@]}"; do
  cat <<EOF >>"$CONFIG_FILE"
  submenuentry "Advanced mode: ${arg%:*}" {
    add_options "${arg#*:}"
  }
EOF
done

for arg in "${RECOVERY_ARGS[@]}"; do
  cat <<EOF >>"$CONFIG_FILE"
  submenuentry "Recovery mode: ${arg%:*}" {
    add_options "$RECOVERY_PARAMETERS ${arg#*:}"
  }
EOF
done

cat <<EOF >>"$CONFIG_FILE"
}

EOF
